repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: detect-private-key
    -   id: pretty-format-json
    -   id: debug-statements
    -   id: name-tests-test
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.17.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^pre_commit/resources/
        args: [--py310-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
-   repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.62
    hooks:
      - id: ty
